### PR TITLE
cleaning up FKP-related changes for new pmesh API

### PR DESCRIPTION
**Pull request by nickhand**
the pandas test case still fails...looking at that now

### CODE REVIEW

**Comment by nickhand** [comment]
@rainwoodman the pandas fail is related to TSC -- it is the only test to use TSC

I can a look at the implementation -- I did the simple test of FFTPower with pure shot noise and the AnisotropicTSC correction, which does not produce a constant power spectrum, so there's probably a bug somewhere

**Comment by nickhand** [comment]
have you tested TSC in pmesh?

**Comment by rainwoodman** [comment]
I did some basic tests. See here

https://github.com/rainwoodman/pmesh/blob/master/pmesh/tests/test_window.py#L156

Maybe that's not right?

**Comment by rainwoodman** [comment]
I'll merge this first. Could you take a look if the TSC implementation is wrong? I added a few more tests and they all look fine to me..

**Pull request merged**
